steps:
  - command: echo "hello world"

  - input: ":ballot_box_with_ballot:"
    prompt: "We robots have questions. Many questions."
    fields:
      - text: "How many steps to create?"
        key: "generated-number"

  - label: ":pipeline:"
    command: ./src/get-steps-from-input.sh | buildkite-agent pipeline upload


