
steps:
  - trigger: roger-that
    label: ":suspect:"
    branches: "main"
    async: true
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
